import type { Property } from "@/src/types/property";

export const LUXURY_PROPERTIES: readonly Property[] = [
  {
    id: "prop-ist-001",
    slug: "bosphorus-penthouse-besiktas",
    title: "بنتهاوس أفق البوسفور",
    shortDescription:
      "بنتهاوس بطابق كامل يطل بانورامياً على المضيق مع تراس خاص.",
    description:
      "إقامة نادرة بطابق كامل فوق البوسفور، بواجهات زجاجية من الأرض إلى السقف ومطبخ للطهاة المحترفين وتراس محيطي مصمم لسهرات الغروب.",
    city: "istanbul",
    district: "بشكتاش",
    price: 185000000,
    currency: "TRY",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 420,
    yearBuilt: 2021,
    propertyType: "penthouse",
    features: [
      "إطلالة على البوسفور",
      "تراس خاص",
      "منزل ذكي",
      "خدمة كونسيرج",
      "موقفا سيارات",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2025-11-12",
    status: "for-sale",
    featured: true,
  },
  {
    id: "prop-ist-002",
    slug: "historic-yali-sariyer",
    title: "قصر يالي مرمَّم على المضيق",
    shortDescription:
      "قصر على الواجهة المائية برصيف خاص على البوسفور الأعلى.",
    description:
      "يالي خشبي مرمَّم بعناية، بأسقف عالية وقاعات استقبال رسمية ومرسى خاص، وهو من أكثر العناوين طلباً على الضفة الأوروبية.",
    city: "istanbul",
    district: "ساريير",
    price: 420000000,
    currency: "TRY",
    bedrooms: 7,
    bathrooms: 6,
    areaSqm: 890,
    yearBuilt: 1912,
    propertyType: "mansion",
    features: [
      "رصيف خاص",
      "أعمال خشبية أصلية",
      "بيت ضيافة",
      "حديقة منسّقة",
      "سكن للعاملين",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2025-10-03",
    status: "for-sale",
    featured: false,
  },
  {
    id: "prop-ist-003",
    slug: "nisantasi-design-residence",
    title: "إقامة نيشانتاشي العصرية",
    shortDescription:
      "شقة عصرية على بعد خطوات من متاجر الرفاهية والمطاعم.",
    description:
      "وحدة زاوية بلمسات برونزية ومساحة معيشة مفتوحة ونجارة مفصّلة حسب الطلب، لمن يريد حيوية المدينة مع هدوء بأجواء فندقية.",
    city: "istanbul",
    district: "نيشانتاشي",
    price: 68500000,
    currency: "TRY",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 195,
    yearBuilt: 2023,
    propertyType: "apartment",
    features: [
      "وحدة زاوية",
      "تدفئة أرضية",
      "مخزن خاص",
      "متاجر عند الباب",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2026-01-08",
    status: "for-sale",
    featured: true,
  },
  {
    id: "prop-ant-001",
    slug: "lara-beachfront-villa",
    title: "فيلا لارا على الشاطئ",
    shortDescription:
      "إطلالة مباشرة على المتوسط مع مسبح لا متناهٍ وكابانا.",
    description:
      "فيلا ساحلية عصرية بإطلالة بحرية مفتوحة وحواجز زجاجية ومطبخ خارجي، على دقائق من منتجعات لارا الخمس نجوم وملاعب الغولف.",
    city: "antalya",
    district: "لارا",
    price: 125000000,
    currency: "TRY",
    bedrooms: 5,
    bathrooms: 5,
    areaSqm: 520,
    yearBuilt: 2022,
    propertyType: "villa",
    features: [
      "وصول مباشر للشاطئ",
      "مسبح لا متناهٍ",
      "مطبخ خارجي",
      "سطح جاهز للطاقة الشمسية",
      "نخيل منسّق",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2025-12-20",
    status: "for-sale",
    featured: true,
  },
  {
    id: "prop-ant-002",
    slug: "kalkan-hillside-villa",
    title: "فيلا كالكان المطلّة على الخليج",
    shortDescription:
      "شرفات متدرجة بإطلالة مفتوحة على الخليج في الساحل الفيروزي.",
    description:
      "منحوتة في سفح التل بشرفات متدرجة ومسبح لا متناهٍ وجدران زجاجية تؤطر خليج كالكان، مناسبة كملاذ خاص أو كعقار للإيجار السياحي.",
    city: "antalya",
    district: "كالكان، قاش",
    price: 89500000,
    currency: "TRY",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 380,
    yearBuilt: 2020,
    propertyType: "villa",
    features: [
      "إطلالة على الخليج",
      "مسبح لا متناهٍ",
      "صالة على السطح",
      "مسافة قصيرة سيراً إلى المارينا",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2025-09-15",
    status: "pending",
    featured: false,
  },
  {
    id: "prop-ant-003",
    slug: "konyaalti-penthouse",
    title: "بنتهاوس كونيالتي الساحلي",
    shortDescription:
      "بنتهاوس دوبلكس قرب شاطئ كونيالتي بتراسين على مستويين.",
    description:
      "تصميم دوبلكس بدرج زجاجي وجناح رئيسي بأجواء السبا وتراسات على الطابقين، على مسافة مشي من الشاطئ ومن الشريط الثقافي في أنطاليا.",
    city: "antalya",
    district: "كونيالتي",
    price: 45200000,
    currency: "TRY",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 240,
    yearBuilt: 2024,
    propertyType: "penthouse",
    features: [
      "تصميم دوبلكس",
      "تراسان",
      "قرب متنزه الشاطئ",
      "شاحن سيارات كهربائية",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
    ],
    listedAt: "2026-02-01",
    status: "for-sale",
    featured: false,
  },
];
