import type { Property } from "@/src/types/property";

export const LUXURY_PROPERTIES: readonly Property[] = [
  {
    id: "prop-ist-001",
    slug: "bosphorus-penthouse-besiktas",
    title: "Bosphorus Sky Penthouse",
    shortDescription:
      "Full-floor penthouse with panoramic strait views and private terrace.",
    description:
      "Rare full-floor residence above the Bosphorus with floor-to-ceiling glazing, chef's kitchen, and a wraparound terrace designed for sunset entertaining.",
    city: "Istanbul",
    district: "Beşiktaş",
    country: "Turkey",
    price: 185000000,
    currency: "TRY",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 420,
    yearBuilt: 2021,
    propertyType: "penthouse",
    features: [
      "Bosphorus view",
      "Private terrace",
      "Smart home",
      "Concierge",
      "Two parking spaces",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2025-11-12",
    status: "for-sale",
  },
  {
    id: "prop-ist-002",
    slug: "historic-yali-sariyer",
    title: "Restored Yalı Estate",
    shortDescription:
      "Waterfront mansion with private dock on the upper Bosphorus.",
    description:
      "Meticulously restored timber yalı with high ceilings, formal reception halls, and a private mooring—one of the most coveted addresses on the European shore.",
    city: "Istanbul",
    district: "Sarıyer",
    country: "Turkey",
    price: 420000000,
    currency: "TRY",
    bedrooms: 7,
    bathrooms: 6,
    areaSqm: 890,
    yearBuilt: 1912,
    propertyType: "mansion",
    features: [
      "Private dock",
      "Original woodwork",
      "Guest house",
      "Landscaped garden",
      "Staff quarters",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2025-10-03",
    status: "for-sale",
  },
  {
    id: "prop-ist-003",
    slug: "nisantasi-design-residence",
    title: "Nişantaşı Design Residence",
    shortDescription:
      "Contemporary apartment steps from luxury retail and dining.",
    description:
      "Corner unit with bronze accents, open-plan living, and bespoke millwork—crafted for buyers who want city energy with calm, hotel-level interiors.",
    city: "Istanbul",
    district: "Nişantaşı",
    country: "Turkey",
    price: 68500000,
    currency: "TRY",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 195,
    yearBuilt: 2023,
    propertyType: "apartment",
    features: [
      "Corner unit",
      "Floor heating",
      "Storage unit",
      "Retail at doorstep",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2026-01-08",
    status: "for-sale",
  },
  {
    id: "prop-ant-001",
    slug: "lara-beachfront-villa",
    title: "Lara Beachfront Villa",
    shortDescription:
      "Direct Mediterranean frontage with infinity pool and cabana.",
    description:
      "Modern coastal villa with uninterrupted sea views, glass railings, and an outdoor kitchen—minutes from Lara’s five-star resorts and golf courses.",
    city: "Antalya",
    district: "Lara",
    country: "Turkey",
    price: 125000000,
    currency: "TRY",
    bedrooms: 5,
    bathrooms: 5,
    areaSqm: 520,
    yearBuilt: 2022,
    propertyType: "villa",
    features: [
      "Beach access",
      "Infinity pool",
      "Outdoor kitchen",
      "Solar-ready roof",
      "Landscaped palms",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2025-12-20",
    status: "for-sale",
  },
  {
    id: "prop-ant-002",
    slug: "kalkan-hillside-villa",
    title: "Kalkan Hillside Infinity Villa",
    shortDescription:
      "Tiered terraces with uninterrupted bay views over the Turquoise Coast.",
    description:
      "Sculpted into the hillside with cascading terraces, an infinity pool, and glass walls that frame Kalkan Bay—ideal as a private retreat or high-yield holiday let.",
    city: "Antalya",
    district: "Kaş (Kalkan)",
    country: "Turkey",
    price: 89500000,
    currency: "TRY",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 380,
    yearBuilt: 2020,
    propertyType: "villa",
    features: [
      "Bay views",
      "Infinity pool",
      "Rooftop lounge",
      "Short walk to marina",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2025-09-15",
    status: "pending",
  },
  {
    id: "prop-ant-003",
    slug: "konyaalti-penthouse",
    title: "Konyaaltı Coastal Penthouse",
    shortDescription:
      "Duplex penthouse near Konyaaltı Beach with dual-level terraces.",
    description:
      "Duplex layout with a glass staircase, spa-inspired primary suite, and terraces on both levels—walking distance to the beach and Antalya’s cultural corridor.",
    city: "Antalya",
    district: "Konyaaltı",
    country: "Turkey",
    price: 45200000,
    currency: "TRY",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 240,
    yearBuilt: 2024,
    propertyType: "penthouse",
    features: [
      "Duplex layout",
      "Dual terraces",
      "Near beach park",
      "EV charging",
    ],
    imageUrls: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    listedAt: "2026-02-01",
    status: "for-sale",
  },
];
